# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Log-Statistics
version:      v0.50.3
version_from: lib/Log/Statistics.pm
installdirs:  site
requires:
    Date::Manip:                   0
    Log::Log4perl:                 0.51
    XML::Writer:                   0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
